# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - name: Gradle dependencies
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dependencies
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: Test Report
        path: build/reports/tests/test
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
